// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PharmacyManagement.Data;

#nullable disable

namespace PharmacyManagement.Backend.Migrations
{
    [DbContext(typeof(PharmacyContext))]
    [Migration("20251225153237_SeedAllTables")]
    partial class SeedAllTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PharmacyManagement.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalSpending")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Ward")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "12 Lê Lợi, Q.1",
                            City = "Hồ Chí Minh",
                            CreatedDate = new DateTime(2025, 12, 25, 22, 32, 37, 257, DateTimeKind.Local).AddTicks(4890),
                            DateOfBirth = new DateTime(1990, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Q.1",
                            Email = "binh.nguyen@gmail.com",
                            Gender = "Nam",
                            IsActive = true,
                            LastModifiedDate = new DateTime(2025, 12, 25, 22, 32, 37, 257, DateTimeKind.Local).AddTicks(4890),
                            Name = "Nguyễn Văn Bình",
                            PhoneNumber = "0987654321",
                            TotalSpending = 500000m,
                            Ward = "Bến Nghé"
                        },
                        new
                        {
                            Id = 2,
                            Address = "34 Nguyễn Trãi, Q.5",
                            City = "Hồ Chí Minh",
                            CreatedDate = new DateTime(2025, 12, 25, 22, 32, 37, 257, DateTimeKind.Local).AddTicks(4890),
                            DateOfBirth = new DateTime(1985, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Q.5",
                            Email = "hoa.tran@gmail.com",
                            Gender = "Nữ",
                            IsActive = true,
                            LastModifiedDate = new DateTime(2025, 12, 25, 22, 32, 37, 257, DateTimeKind.Local).AddTicks(4890),
                            Name = "Trần Thị Hoa",
                            PhoneNumber = "0978123456",
                            TotalSpending = 350000m,
                            Ward = "Phạm Ngũ Lão"
                        });
                });

            modelBuilder.Entity("PharmacyManagement.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserAccountId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserAccountId")
                        .IsUnique();

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2025, 12, 25, 22, 32, 37, 257, DateTimeKind.Local).AddTicks(4890),
                            Department = "Bán hàng",
                            Email = "nhanvien@example.com",
                            FullName = "Nhân Viên Mặc Định",
                            LastModifiedDate = new DateTime(2025, 12, 25, 22, 32, 37, 257, DateTimeKind.Local).AddTicks(4890),
                            PhoneNumber = "0123456789",
                            Position = "Nhân Viên",
                            Salary = 10000000m,
                            StartDate = new DateTime(2025, 12, 25, 22, 32, 37, 257, DateTimeKind.Local).AddTicks(4890),
                            Status = "Active",
                            UserAccountId = "f15eee25-c953-4dd3-9e46-95ac317bccb5"
                        });
                });

            modelBuilder.Entity("PharmacyManagement.Models.InventoryHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("MedicineId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StockAfter")
                        .HasColumnType("int");

                    b.Property<int>("StockBefore")
                        .HasColumnType("int");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MedicineId");

                    b.ToTable("InventoryHistories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2025, 12, 15, 22, 32, 37, 257, DateTimeKind.Local).AddTicks(4890),
                            MedicineId = 1,
                            Notes = "",
                            Quantity = 100,
                            Reason = "Nhập hàng",
                            StockAfter = 200,
                            StockBefore = 100,
                            TransactionType = "Import"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2025, 12, 15, 22, 32, 37, 257, DateTimeKind.Local).AddTicks(4890),
                            MedicineId = 2,
                            Notes = "",
                            Quantity = 50,
                            Reason = "Nhập hàng",
                            StockAfter = 150,
                            StockBefore = 100,
                            TransactionType = "Import"
                        });
                });

            modelBuilder.Entity("PharmacyManagement.Models.Medicine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CurrentStock")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dosage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MedicineGroupId")
                        .HasColumnType("int");

                    b.Property<int>("MinStockLevel")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Usage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MedicineGroupId");

                    b.ToTable("Medicines");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Barcode = "8935206000012",
                            CreatedDate = new DateTime(2025, 12, 25, 22, 32, 37, 257, DateTimeKind.Local).AddTicks(4890),
                            CurrentStock = 200,
                            Description = "Thuốc hạ sốt, giảm đau",
                            Dosage = "1 viên/lần, 2-3 lần/ngày",
                            ExpiryDate = new DateTime(2027, 12, 25, 22, 32, 37, 257, DateTimeKind.Local).AddTicks(4890),
                            IsActive = true,
                            LastModifiedDate = new DateTime(2025, 12, 25, 22, 32, 37, 257, DateTimeKind.Local).AddTicks(4890),
                            Manufacturer = "DHG Pharma",
                            MedicineGroupId = 3,
                            MinStockLevel = 20,
                            Name = "Paracetamol 500mg",
                            Price = 1500m,
                            Unit = "Viên",
                            Usage = "Uống sau ăn"
                        },
                        new
                        {
                            Id = 2,
                            Barcode = "8935206000029",
                            CreatedDate = new DateTime(2025, 12, 25, 22, 32, 37, 257, DateTimeKind.Local).AddTicks(4890),
                            CurrentStock = 150,
                            Description = "Kháng sinh phổ rộng",
                            Dosage = "1 viên/lần, 2 lần/ngày",
                            ExpiryDate = new DateTime(2027, 12, 25, 22, 32, 37, 257, DateTimeKind.Local).AddTicks(4890),
                            IsActive = true,
                            LastModifiedDate = new DateTime(2025, 12, 25, 22, 32, 37, 257, DateTimeKind.Local).AddTicks(4890),
                            Manufacturer = "Stada",
                            MedicineGroupId = 1,
                            MinStockLevel = 15,
                            Name = "Amoxicillin 500mg",
                            Price = 2500m,
                            Unit = "Viên",
                            Usage = "Uống trước ăn"
                        },
                        new
                        {
                            Id = 3,
                            Barcode = "8935206000036",
                            CreatedDate = new DateTime(2025, 12, 25, 22, 32, 37, 257, DateTimeKind.Local).AddTicks(4890),
                            CurrentStock = 300,
                            Description = "Tăng sức đề kháng",
                            Dosage = "1 viên/ngày",
                            ExpiryDate = new DateTime(2027, 12, 25, 22, 32, 37, 257, DateTimeKind.Local).AddTicks(4890),
                            IsActive = true,
                            LastModifiedDate = new DateTime(2025, 12, 25, 22, 32, 37, 257, DateTimeKind.Local).AddTicks(4890),
                            Manufacturer = "Traphaco",
                            MedicineGroupId = 4,
                            MinStockLevel = 30,
                            Name = "Vitamin C 500mg",
                            Price = 1200m,
                            Unit = "Viên",
                            Usage = "Uống sau ăn"
                        },
                        new
                        {
                            Id = 4,
                            Barcode = "8935206000043",
                            CreatedDate = new DateTime(2025, 12, 25, 22, 32, 37, 257, DateTimeKind.Local).AddTicks(4890),
                            CurrentStock = 100,
                            Description = "Điều trị tiêu chảy",
                            Dosage = "1 gói/lần, 2 lần/ngày",
                            ExpiryDate = new DateTime(2027, 12, 25, 22, 32, 37, 257, DateTimeKind.Local).AddTicks(4890),
                            IsActive = true,
                            LastModifiedDate = new DateTime(2025, 12, 25, 22, 32, 37, 257, DateTimeKind.Local).AddTicks(4890),
                            Manufacturer = "Ipsen",
                            MedicineGroupId = 5,
                            MinStockLevel = 10,
                            Name = "Smecta",
                            Price = 8000m,
                            Unit = "Gói",
                            Usage = "Pha với nước"
                        },
                        new
                        {
                            Id = 5,
                            Barcode = "8935206000050",
                            CreatedDate = new DateTime(2025, 12, 25, 22, 32, 37, 257, DateTimeKind.Local).AddTicks(4890),
                            CurrentStock = 120,
                            Description = "Giảm đau, hạ sốt",
                            Dosage = "1 viên/lần, 2 lần/ngày",
                            ExpiryDate = new DateTime(2027, 12, 25, 22, 32, 37, 257, DateTimeKind.Local).AddTicks(4890),
                            IsActive = true,
                            LastModifiedDate = new DateTime(2025, 12, 25, 22, 32, 37, 257, DateTimeKind.Local).AddTicks(4890),
                            Manufacturer = "Sanofi",
                            MedicineGroupId = 2,
                            MinStockLevel = 12,
                            Name = "Ibuprofen 400mg",
                            Price = 2000m,
                            Unit = "Viên",
                            Usage = "Uống sau ăn"
                        });
                });

            modelBuilder.Entity("PharmacyManagement.Models.MedicineGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MedicineGroups");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Nhóm thuốc kháng sinh",
                            IsActive = true,
                            Name = "Kháng sinh"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Nhóm thuốc giảm đau",
                            IsActive = true,
                            Name = "Giảm đau"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Nhóm thuốc hạ sốt",
                            IsActive = true,
                            Name = "Hạ sốt"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Nhóm vitamin",
                            IsActive = true,
                            Name = "Vitamin"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Nhóm thuốc tiêu hóa",
                            IsActive = true,
                            Name = "Tiêu hóa"
                        });
                });

            modelBuilder.Entity("PharmacyManagement.Models.MedicinePromotion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MedicineId")
                        .HasColumnType("int");

                    b.Property<int>("PromotionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MedicineId");

                    b.HasIndex("PromotionId");

                    b.ToTable("MedicinePromotions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MedicineId = 3,
                            PromotionId = 2
                        });
                });

            modelBuilder.Entity("PharmacyManagement.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NotificationType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecipientType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Notifications");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2025, 12, 25, 22, 32, 37, 257, DateTimeKind.Local).AddTicks(4890),
                            EmployeeId = 1,
                            IsRead = false,
                            Message = "Paracetamol 500mg sắp hết hàng.",
                            NotificationType = "Stock",
                            RecipientType = "Employee",
                            Title = "Hết hàng Paracetamol"
                        });
                });

            modelBuilder.Entity("PharmacyManagement.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Tax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2025, 12, 23, 22, 32, 37, 257, DateTimeKind.Local).AddTicks(4890),
                            CustomerId = 1,
                            Discount = 10000m,
                            EmployeeId = 1,
                            Notes = "",
                            OrderCode = "ORD0001",
                            OrderDate = new DateTime(2025, 12, 23, 22, 32, 37, 257, DateTimeKind.Local).AddTicks(4890),
                            OrderStatus = "Completed",
                            PaymentMethod = "Cash",
                            SubTotal = 100000m,
                            Tax = 1000m,
                            Total = 91000m
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2025, 12, 24, 22, 32, 37, 257, DateTimeKind.Local).AddTicks(4890),
                            CustomerId = 2,
                            Discount = 20000m,
                            EmployeeId = 1,
                            Notes = "",
                            OrderCode = "ORD0002",
                            OrderDate = new DateTime(2025, 12, 24, 22, 32, 37, 257, DateTimeKind.Local).AddTicks(4890),
                            OrderStatus = "Completed",
                            PaymentMethod = "Card",
                            SubTotal = 200000m,
                            Tax = 2000m,
                            Total = 182000m
                        });
                });

            modelBuilder.Entity("PharmacyManagement.Models.OrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MedicineId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("MedicineId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderDetails");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MedicineId = 1,
                            OrderId = 1,
                            Quantity = 10,
                            TotalPrice = 15000m,
                            UnitPrice = 1500m
                        },
                        new
                        {
                            Id = 2,
                            MedicineId = 3,
                            OrderId = 1,
                            Quantity = 5,
                            TotalPrice = 6000m,
                            UnitPrice = 1200m
                        },
                        new
                        {
                            Id = 3,
                            MedicineId = 2,
                            OrderId = 2,
                            Quantity = 20,
                            TotalPrice = 50000m,
                            UnitPrice = 2500m
                        },
                        new
                        {
                            Id = 4,
                            MedicineId = 4,
                            OrderId = 2,
                            Quantity = 10,
                            TotalPrice = 80000m,
                            UnitPrice = 8000m
                        });
                });

            modelBuilder.Entity("PharmacyManagement.Models.Promotion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("DiscountValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPercentage")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("MinOrderAmount")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PromotionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TargetCustomer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Promotions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2025, 12, 25, 22, 32, 37, 257, DateTimeKind.Local).AddTicks(4890),
                            Description = "Giảm 10% cho đơn từ 200k",
                            DiscountValue = 10m,
                            EndDate = new DateTime(2026, 1, 14, 22, 32, 37, 257, DateTimeKind.Local).AddTicks(4890),
                            IsActive = true,
                            IsPercentage = true,
                            LastModifiedDate = new DateTime(2025, 12, 25, 22, 32, 37, 257, DateTimeKind.Local).AddTicks(4890),
                            MinOrderAmount = 200000,
                            Name = "Giảm giá mùa hè",
                            PromotionType = "Discount",
                            StartDate = new DateTime(2025, 12, 15, 22, 32, 37, 257, DateTimeKind.Local).AddTicks(4890),
                            TargetCustomer = "All"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2025, 12, 25, 22, 32, 37, 257, DateTimeKind.Local).AddTicks(4890),
                            Description = "Tặng 1 hộp Vitamin C cho đơn trên 500k",
                            DiscountValue = 0m,
                            EndDate = new DateTime(2026, 1, 19, 22, 32, 37, 257, DateTimeKind.Local).AddTicks(4890),
                            IsActive = true,
                            IsPercentage = false,
                            LastModifiedDate = new DateTime(2025, 12, 25, 22, 32, 37, 257, DateTimeKind.Local).AddTicks(4890),
                            MinOrderAmount = 500000,
                            Name = "Tặng Vitamin C",
                            PromotionType = "Gift",
                            StartDate = new DateTime(2025, 12, 20, 22, 32, 37, 257, DateTimeKind.Local).AddTicks(4890),
                            TargetCustomer = "VIP"
                        });
                });

            modelBuilder.Entity("PharmacyManagement.Models.PurchaseOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DeliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PurchaseOrderCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalCost")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("SupplierId");

                    b.ToTable("PurchaseOrders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2025, 12, 15, 22, 32, 37, 257, DateTimeKind.Local).AddTicks(4890),
                            DeliveryDate = new DateTime(2025, 12, 17, 22, 32, 37, 257, DateTimeKind.Local).AddTicks(4890),
                            Notes = "",
                            OrderDate = new DateTime(2025, 12, 15, 22, 32, 37, 257, DateTimeKind.Local).AddTicks(4890),
                            PurchaseOrderCode = "PO0001",
                            Status = "Received",
                            SupplierId = 1,
                            TotalCost = 1000000m
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2025, 12, 18, 22, 32, 37, 257, DateTimeKind.Local).AddTicks(4890),
                            DeliveryDate = new DateTime(2025, 12, 20, 22, 32, 37, 257, DateTimeKind.Local).AddTicks(4890),
                            Notes = "",
                            OrderDate = new DateTime(2025, 12, 18, 22, 32, 37, 257, DateTimeKind.Local).AddTicks(4890),
                            PurchaseOrderCode = "PO0002",
                            Status = "Received",
                            SupplierId = 2,
                            TotalCost = 500000m
                        });
                });

            modelBuilder.Entity("PharmacyManagement.Models.PurchaseOrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MedicineId")
                        .HasColumnType("int");

                    b.Property<int>("PurchaseOrderId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitCost")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("MedicineId");

                    b.HasIndex("PurchaseOrderId");

                    b.ToTable("PurchaseOrderDetails");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MedicineId = 1,
                            PurchaseOrderId = 1,
                            Quantity = 100,
                            TotalCost = 120000m,
                            UnitCost = 1200m
                        },
                        new
                        {
                            Id = 2,
                            MedicineId = 2,
                            PurchaseOrderId = 1,
                            Quantity = 50,
                            TotalCost = 100000m,
                            UnitCost = 2000m
                        },
                        new
                        {
                            Id = 3,
                            MedicineId = 3,
                            PurchaseOrderId = 2,
                            Quantity = 200,
                            TotalCost = 200000m,
                            UnitCost = 1000m
                        });
                });

            modelBuilder.Entity("PharmacyManagement.Models.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactPerson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Debt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaxNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Suppliers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "288 Bis Nguyễn Văn Cừ, Cần Thơ",
                            City = "Cần Thơ",
                            ContactPerson = "Nguyễn Văn A",
                            CreatedDate = new DateTime(2025, 12, 25, 22, 32, 37, 257, DateTimeKind.Local).AddTicks(4890),
                            Debt = 0m,
                            Email = "contact@dhgpharma.com.vn",
                            IsActive = true,
                            LastModifiedDate = new DateTime(2025, 12, 25, 22, 32, 37, 257, DateTimeKind.Local).AddTicks(4890),
                            Name = "Công ty Dược Hậu Giang",
                            PhoneNumber = "0909123456",
                            TaxNumber = "1800106840"
                        },
                        new
                        {
                            Id = 2,
                            Address = "75 Yên Ninh, Hà Nội",
                            City = "Hà Nội",
                            ContactPerson = "Trần Thị B",
                            CreatedDate = new DateTime(2025, 12, 25, 22, 32, 37, 257, DateTimeKind.Local).AddTicks(4890),
                            Debt = 0m,
                            Email = "info@traphaco.com.vn",
                            IsActive = true,
                            LastModifiedDate = new DateTime(2025, 12, 25, 22, 32, 37, 257, DateTimeKind.Local).AddTicks(4890),
                            Name = "Công ty Traphaco",
                            PhoneNumber = "0912345678",
                            TaxNumber = "0100108656"
                        });
                });

            modelBuilder.Entity("PharmacyManagement.Models.UserAccount", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastLoginDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserAccounts");

                    b.HasData(
                        new
                        {
                            Id = "d2af3ead-cbe2-42c8-b4b9-636f8340e9be",
                            CreatedDate = new DateTime(2025, 12, 25, 22, 32, 37, 257, DateTimeKind.Local).AddTicks(4890),
                            Email = "admin@example.com",
                            IsActive = true,
                            LastLoginDate = new DateTime(2025, 12, 25, 22, 32, 37, 257, DateTimeKind.Local).AddTicks(4890),
                            PasswordHash = "AQAAAAEAACcQAAAAEJ6Qw1n6Qw1n6Qw1n6Qw1n6Qw1n6Qw1n6Qw1n6Qw1n6Qw1n6Qw1n6Qw1n6Qw1n6Qw==",
                            Role = "Admin",
                            Username = "Admin123"
                        },
                        new
                        {
                            Id = "f15eee25-c953-4dd3-9e46-95ac317bccb5",
                            CreatedDate = new DateTime(2025, 12, 25, 22, 32, 37, 257, DateTimeKind.Local).AddTicks(4890),
                            Email = "nhanvien@example.com",
                            IsActive = true,
                            LastLoginDate = new DateTime(2025, 12, 25, 22, 32, 37, 257, DateTimeKind.Local).AddTicks(4890),
                            PasswordHash = "AQAAAAEAACcQAAAAEJ6Qw1n6Qw1n6Qw1n6Qw1n6Qw1n6Qw1n6Qw1n6Qw1n6Qw1n6Qw1n6Qw1n6Qw1n6Qw==",
                            Role = "Employee",
                            Username = "NhanVien123"
                        });
                });

            modelBuilder.Entity("PharmacyManagement.Models.WorkHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrdersProcessed")
                        .HasColumnType("int");

                    b.Property<decimal>("Revenue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Shift")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("WorkDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("WorkHistories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2025, 12, 24, 22, 32, 37, 257, DateTimeKind.Local).AddTicks(4890),
                            EmployeeId = 1,
                            Notes = "",
                            OrdersProcessed = 5,
                            Revenue = 500000m,
                            Shift = "Morning",
                            WorkDate = new DateTime(2025, 12, 24, 22, 32, 37, 257, DateTimeKind.Local).AddTicks(4890)
                        });
                });

            modelBuilder.Entity("PharmacyManagement.Models.Employee", b =>
                {
                    b.HasOne("PharmacyManagement.Models.UserAccount", "UserAccount")
                        .WithOne("Employee")
                        .HasForeignKey("PharmacyManagement.Models.Employee", "UserAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("PharmacyManagement.Models.InventoryHistory", b =>
                {
                    b.HasOne("PharmacyManagement.Models.Medicine", "Medicine")
                        .WithMany("InventoryHistories")
                        .HasForeignKey("MedicineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Medicine");
                });

            modelBuilder.Entity("PharmacyManagement.Models.Medicine", b =>
                {
                    b.HasOne("PharmacyManagement.Models.MedicineGroup", "MedicineGroup")
                        .WithMany("Medicines")
                        .HasForeignKey("MedicineGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MedicineGroup");
                });

            modelBuilder.Entity("PharmacyManagement.Models.MedicinePromotion", b =>
                {
                    b.HasOne("PharmacyManagement.Models.Medicine", "Medicine")
                        .WithMany()
                        .HasForeignKey("MedicineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PharmacyManagement.Models.Promotion", "Promotion")
                        .WithMany("MedicinePromotions")
                        .HasForeignKey("PromotionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medicine");

                    b.Navigation("Promotion");
                });

            modelBuilder.Entity("PharmacyManagement.Models.Order", b =>
                {
                    b.HasOne("PharmacyManagement.Models.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PharmacyManagement.Models.Employee", "Employee")
                        .WithMany("Orders")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("PharmacyManagement.Models.OrderDetail", b =>
                {
                    b.HasOne("PharmacyManagement.Models.Medicine", "Medicine")
                        .WithMany("OrderDetails")
                        .HasForeignKey("MedicineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PharmacyManagement.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medicine");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("PharmacyManagement.Models.PurchaseOrder", b =>
                {
                    b.HasOne("PharmacyManagement.Models.Supplier", "Supplier")
                        .WithMany("PurchaseOrders")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("PharmacyManagement.Models.PurchaseOrderDetail", b =>
                {
                    b.HasOne("PharmacyManagement.Models.Medicine", "Medicine")
                        .WithMany()
                        .HasForeignKey("MedicineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PharmacyManagement.Models.PurchaseOrder", "PurchaseOrder")
                        .WithMany("PurchaseOrderDetails")
                        .HasForeignKey("PurchaseOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medicine");

                    b.Navigation("PurchaseOrder");
                });

            modelBuilder.Entity("PharmacyManagement.Models.WorkHistory", b =>
                {
                    b.HasOne("PharmacyManagement.Models.Employee", "Employee")
                        .WithMany("WorkHistories")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("PharmacyManagement.Models.Customer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("PharmacyManagement.Models.Employee", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("WorkHistories");
                });

            modelBuilder.Entity("PharmacyManagement.Models.Medicine", b =>
                {
                    b.Navigation("InventoryHistories");

                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("PharmacyManagement.Models.MedicineGroup", b =>
                {
                    b.Navigation("Medicines");
                });

            modelBuilder.Entity("PharmacyManagement.Models.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("PharmacyManagement.Models.Promotion", b =>
                {
                    b.Navigation("MedicinePromotions");
                });

            modelBuilder.Entity("PharmacyManagement.Models.PurchaseOrder", b =>
                {
                    b.Navigation("PurchaseOrderDetails");
                });

            modelBuilder.Entity("PharmacyManagement.Models.Supplier", b =>
                {
                    b.Navigation("PurchaseOrders");
                });

            modelBuilder.Entity("PharmacyManagement.Models.UserAccount", b =>
                {
                    b.Navigation("Employee")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
