// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PharmacyManagement.Data;

#nullable disable

namespace PharmacyManagement.Backend.Migrations
{
    [DbContext(typeof(PharmacyContext))]
    partial class PharmacyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PharmacyManagement.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("District")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalSpending")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Ward")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "HCM",
                            City = "HCM",
                            CreatedDate = new DateTime(2026, 1, 1, 19, 52, 55, 933, DateTimeKind.Local).AddTicks(4584),
                            DateOfBirth = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Q1",
                            Email = "binh@gmail.com",
                            Gender = "Nam",
                            IsActive = true,
                            LastModifiedDate = new DateTime(2026, 1, 1, 19, 52, 55, 933, DateTimeKind.Local).AddTicks(4584),
                            Name = "Nguyễn Văn Bình",
                            PhoneNumber = "0987654321",
                            TotalSpending = 500000m,
                            Ward = "Ben Nghe"
                        },
                        new
                        {
                            Id = 2,
                            Address = "HN",
                            City = "HN",
                            CreatedDate = new DateTime(2026, 1, 1, 19, 52, 55, 933, DateTimeKind.Local).AddTicks(4584),
                            DateOfBirth = new DateTime(1995, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "HK",
                            Email = "hoa@gmail.com",
                            Gender = "Nu",
                            IsActive = true,
                            LastModifiedDate = new DateTime(2026, 1, 1, 19, 52, 55, 933, DateTimeKind.Local).AddTicks(4584),
                            Name = "Trần Thị Hoa",
                            PhoneNumber = "0978123456",
                            TotalSpending = 350000m,
                            Ward = "Hang Bai"
                        });
                });

            modelBuilder.Entity("PharmacyManagement.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Salary")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserAccountId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserAccountId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2026, 1, 1, 19, 52, 55, 933, DateTimeKind.Local).AddTicks(4584),
                            Department = "Bán hàng",
                            Email = "nhanvien@example.com",
                            FullName = "Nhân Viên Bán Hàng",
                            LastModifiedDate = new DateTime(2026, 1, 1, 19, 52, 55, 933, DateTimeKind.Local).AddTicks(4584),
                            PhoneNumber = "0123456789",
                            Position = "Nhân Viên",
                            Salary = 10000000m,
                            StartDate = new DateTime(2026, 1, 1, 19, 52, 55, 933, DateTimeKind.Local).AddTicks(4584),
                            Status = "Active",
                            UserAccountId = 2
                        });
                });

            modelBuilder.Entity("PharmacyManagement.Models.InventoryHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("MedicineId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StockAfter")
                        .HasColumnType("int");

                    b.Property<int>("StockBefore")
                        .HasColumnType("int");

                    b.Property<string>("TransactionType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MedicineId");

                    b.ToTable("InventoryHistories");
                });

            modelBuilder.Entity("PharmacyManagement.Models.Medicine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Barcode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CurrentStock")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dosage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MedicineGroupId")
                        .HasColumnType("int");

                    b.Property<int>("MinStockLevel")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Unit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Usage")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MedicineGroupId");

                    b.ToTable("Medicines");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Barcode = "8935206000012",
                            CreatedDate = new DateTime(2026, 1, 1, 19, 52, 55, 933, DateTimeKind.Local).AddTicks(4584),
                            CurrentStock = 200,
                            Description = "Thuốc hạ sốt",
                            Dosage = "1 viên/lần",
                            ExpiryDate = new DateTime(2028, 1, 1, 19, 52, 55, 933, DateTimeKind.Local).AddTicks(4584),
                            IsActive = true,
                            LastModifiedDate = new DateTime(2026, 1, 1, 19, 52, 55, 933, DateTimeKind.Local).AddTicks(4584),
                            Manufacturer = "DHG Pharma",
                            MedicineGroupId = 3,
                            MinStockLevel = 20,
                            Name = "Paracetamol 500mg",
                            Price = 1500m,
                            Unit = "Viên",
                            Usage = "Uống sau ăn"
                        },
                        new
                        {
                            Id = 2,
                            Barcode = "8935206000029",
                            CreatedDate = new DateTime(2026, 1, 1, 19, 52, 55, 933, DateTimeKind.Local).AddTicks(4584),
                            CurrentStock = 150,
                            Description = "Kháng sinh",
                            Dosage = "1 viên/lần",
                            ExpiryDate = new DateTime(2028, 1, 1, 19, 52, 55, 933, DateTimeKind.Local).AddTicks(4584),
                            IsActive = true,
                            LastModifiedDate = new DateTime(2026, 1, 1, 19, 52, 55, 933, DateTimeKind.Local).AddTicks(4584),
                            Manufacturer = "Stada",
                            MedicineGroupId = 1,
                            MinStockLevel = 15,
                            Name = "Amoxicillin 500mg",
                            Price = 2500m,
                            Unit = "Viên",
                            Usage = "Uống trước ăn"
                        },
                        new
                        {
                            Id = 3,
                            Barcode = "8935206000036",
                            CreatedDate = new DateTime(2026, 1, 1, 19, 52, 55, 933, DateTimeKind.Local).AddTicks(4584),
                            CurrentStock = 300,
                            Description = "Tăng đề kháng",
                            Dosage = "1 viên/ngày",
                            ExpiryDate = new DateTime(2028, 1, 1, 19, 52, 55, 933, DateTimeKind.Local).AddTicks(4584),
                            IsActive = true,
                            LastModifiedDate = new DateTime(2026, 1, 1, 19, 52, 55, 933, DateTimeKind.Local).AddTicks(4584),
                            Manufacturer = "Traphaco",
                            MedicineGroupId = 4,
                            MinStockLevel = 30,
                            Name = "Vitamin C 500mg",
                            Price = 1200m,
                            Unit = "Viên",
                            Usage = "Uống sau ăn"
                        },
                        new
                        {
                            Id = 4,
                            Barcode = "8935206000043",
                            CreatedDate = new DateTime(2026, 1, 1, 19, 52, 55, 933, DateTimeKind.Local).AddTicks(4584),
                            CurrentStock = 100,
                            Description = "Trị tiêu chảy",
                            Dosage = "1 gói/lần",
                            ExpiryDate = new DateTime(2028, 1, 1, 19, 52, 55, 933, DateTimeKind.Local).AddTicks(4584),
                            IsActive = true,
                            LastModifiedDate = new DateTime(2026, 1, 1, 19, 52, 55, 933, DateTimeKind.Local).AddTicks(4584),
                            Manufacturer = "Ipsen",
                            MedicineGroupId = 5,
                            MinStockLevel = 10,
                            Name = "Smecta",
                            Price = 8000m,
                            Unit = "Gói",
                            Usage = "Pha nước"
                        },
                        new
                        {
                            Id = 5,
                            Barcode = "8935206000050",
                            CreatedDate = new DateTime(2026, 1, 1, 19, 52, 55, 933, DateTimeKind.Local).AddTicks(4584),
                            CurrentStock = 120,
                            Description = "Giảm đau",
                            Dosage = "1 viên/lần",
                            ExpiryDate = new DateTime(2028, 1, 1, 19, 52, 55, 933, DateTimeKind.Local).AddTicks(4584),
                            IsActive = true,
                            LastModifiedDate = new DateTime(2026, 1, 1, 19, 52, 55, 933, DateTimeKind.Local).AddTicks(4584),
                            Manufacturer = "Sanofi",
                            MedicineGroupId = 2,
                            MinStockLevel = 12,
                            Name = "Ibuprofen 400mg",
                            Price = 2000m,
                            Unit = "Viên",
                            Usage = "Uống sau ăn"
                        });
                });

            modelBuilder.Entity("PharmacyManagement.Models.MedicineGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MedicineGroups");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Nhóm thuốc kháng sinh",
                            IsActive = true,
                            Name = "Kháng sinh"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Nhóm thuốc giảm đau",
                            IsActive = true,
                            Name = "Giảm đau"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Nhóm thuốc hạ sốt",
                            IsActive = true,
                            Name = "Hạ sốt"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Nhóm vitamin",
                            IsActive = true,
                            Name = "Vitamin"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Nhóm thuốc tiêu hóa",
                            IsActive = true,
                            Name = "Tiêu hóa"
                        });
                });

            modelBuilder.Entity("PharmacyManagement.Models.MedicinePromotion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MedicineId")
                        .HasColumnType("int");

                    b.Property<int>("PromotionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MedicineId");

                    b.HasIndex("PromotionId");

                    b.ToTable("MedicinePromotions");
                });

            modelBuilder.Entity("PharmacyManagement.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NotificationType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecipientType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("PharmacyManagement.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<decimal>("Discount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SubTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Tax")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2025, 12, 31, 19, 52, 55, 933, DateTimeKind.Local).AddTicks(4584),
                            CustomerId = 1,
                            Discount = 0m,
                            EmployeeId = 1,
                            Notes = "Khách quen",
                            OrderCode = "HD001",
                            OrderDate = new DateTime(2025, 12, 31, 19, 52, 55, 933, DateTimeKind.Local).AddTicks(4584),
                            OrderStatus = "Completed",
                            PaymentMethod = "Cash",
                            SubTotal = 150000m,
                            Tax = 0m,
                            Total = 150000m
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2026, 1, 1, 19, 52, 55, 933, DateTimeKind.Local).AddTicks(4584),
                            CustomerId = 2,
                            Discount = 20000m,
                            EmployeeId = 1,
                            Notes = "",
                            OrderCode = "HD002",
                            OrderDate = new DateTime(2026, 1, 1, 19, 52, 55, 933, DateTimeKind.Local).AddTicks(4584),
                            OrderStatus = "Completed",
                            PaymentMethod = "Card",
                            SubTotal = 200000m,
                            Tax = 0m,
                            Total = 180000m
                        });
                });

            modelBuilder.Entity("PharmacyManagement.Models.OrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MedicineId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("MedicineId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderDetails");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MedicineId = 1,
                            OrderId = 1,
                            Quantity = 10,
                            TotalPrice = 15000m,
                            UnitPrice = 1500m
                        },
                        new
                        {
                            Id = 2,
                            MedicineId = 2,
                            OrderId = 2,
                            Quantity = 5,
                            TotalPrice = 12500m,
                            UnitPrice = 2500m
                        });
                });

            modelBuilder.Entity("PharmacyManagement.Models.Promotion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("DiscountValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPercentage")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("MinOrderAmount")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PromotionType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TargetCustomer")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Promotions");
                });

            modelBuilder.Entity("PharmacyManagement.Models.PurchaseOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DeliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PurchaseOrderCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("SupplierId");

                    b.ToTable("PurchaseOrders");
                });

            modelBuilder.Entity("PharmacyManagement.Models.PurchaseOrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MedicineId")
                        .HasColumnType("int");

                    b.Property<int>("PurchaseOrderId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("MedicineId");

                    b.HasIndex("PurchaseOrderId");

                    b.ToTable("PurchaseOrderDetails");
                });

            modelBuilder.Entity("PharmacyManagement.Models.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactPerson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Debt")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaxNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("PharmacyManagement.Models.UserAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordAccount")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserAccounts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2026, 1, 1, 19, 52, 55, 933, DateTimeKind.Local).AddTicks(4584),
                            Email = "admin@example.com",
                            IsActive = true,
                            PasswordAccount = "123",
                            Role = "Admin",
                            Username = "Admin123"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2026, 1, 1, 19, 52, 55, 933, DateTimeKind.Local).AddTicks(4584),
                            Email = "nhanvien@example.com",
                            IsActive = true,
                            PasswordAccount = "123",
                            Role = "Employee",
                            Username = "NhanVien123"
                        });
                });

            modelBuilder.Entity("PharmacyManagement.Models.WorkHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrdersProcessed")
                        .HasColumnType("int");

                    b.Property<decimal>("Revenue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Shift")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("WorkDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("WorkHistories");
                });

            modelBuilder.Entity("PharmacyManagement.Models.Employee", b =>
                {
                    b.HasOne("PharmacyManagement.Models.UserAccount", "UserAccount")
                        .WithMany()
                        .HasForeignKey("UserAccountId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("PharmacyManagement.Models.InventoryHistory", b =>
                {
                    b.HasOne("PharmacyManagement.Models.Medicine", "Medicine")
                        .WithMany("InventoryHistories")
                        .HasForeignKey("MedicineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medicine");
                });

            modelBuilder.Entity("PharmacyManagement.Models.Medicine", b =>
                {
                    b.HasOne("PharmacyManagement.Models.MedicineGroup", "MedicineGroup")
                        .WithMany("Medicines")
                        .HasForeignKey("MedicineGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MedicineGroup");
                });

            modelBuilder.Entity("PharmacyManagement.Models.MedicinePromotion", b =>
                {
                    b.HasOne("PharmacyManagement.Models.Medicine", "Medicine")
                        .WithMany()
                        .HasForeignKey("MedicineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PharmacyManagement.Models.Promotion", "Promotion")
                        .WithMany("MedicinePromotions")
                        .HasForeignKey("PromotionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medicine");

                    b.Navigation("Promotion");
                });

            modelBuilder.Entity("PharmacyManagement.Models.Order", b =>
                {
                    b.HasOne("PharmacyManagement.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId");

                    b.HasOne("PharmacyManagement.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Customer");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("PharmacyManagement.Models.OrderDetail", b =>
                {
                    b.HasOne("PharmacyManagement.Models.Medicine", "Medicine")
                        .WithMany()
                        .HasForeignKey("MedicineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PharmacyManagement.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medicine");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("PharmacyManagement.Models.PurchaseOrder", b =>
                {
                    b.HasOne("PharmacyManagement.Models.Supplier", "Supplier")
                        .WithMany("PurchaseOrders")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("PharmacyManagement.Models.PurchaseOrderDetail", b =>
                {
                    b.HasOne("PharmacyManagement.Models.Medicine", "Medicine")
                        .WithMany()
                        .HasForeignKey("MedicineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PharmacyManagement.Models.PurchaseOrder", "PurchaseOrder")
                        .WithMany("PurchaseOrderDetails")
                        .HasForeignKey("PurchaseOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medicine");

                    b.Navigation("PurchaseOrder");
                });

            modelBuilder.Entity("PharmacyManagement.Models.WorkHistory", b =>
                {
                    b.HasOne("PharmacyManagement.Models.Employee", "Employee")
                        .WithMany("WorkHistories")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("PharmacyManagement.Models.Employee", b =>
                {
                    b.Navigation("WorkHistories");
                });

            modelBuilder.Entity("PharmacyManagement.Models.Medicine", b =>
                {
                    b.Navigation("InventoryHistories");
                });

            modelBuilder.Entity("PharmacyManagement.Models.MedicineGroup", b =>
                {
                    b.Navigation("Medicines");
                });

            modelBuilder.Entity("PharmacyManagement.Models.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("PharmacyManagement.Models.Promotion", b =>
                {
                    b.Navigation("MedicinePromotions");
                });

            modelBuilder.Entity("PharmacyManagement.Models.PurchaseOrder", b =>
                {
                    b.Navigation("PurchaseOrderDetails");
                });

            modelBuilder.Entity("PharmacyManagement.Models.Supplier", b =>
                {
                    b.Navigation("PurchaseOrders");
                });
#pragma warning restore 612, 618
        }
    }
}
